# Generated by Django 5.0.6 on 2026-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgrecord',
            name='confidence',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
